### ISSUE TITLE
Create or join GitHub Organization

### ISSUE THREAD

**Issue by webdevilopers** [webdevilopers/php-ddd#10]
Hello @juliendufresne!

We recognized you already create a great organization here:
https://github.com/php-ddd

And you already added some @symfony bundle integrations:
- https://github.com/php-ddd/domain-driven-design-bundle
- https://github.com/php-ddd/php-ddd-bundle

Are you interested in joining us resp. adding us to your organization? Feel free to ask me or @yvoyer about our plans. Just comment here or send us a DM on twitter. Thanks!

- http://twitter.com/webdevilopers
- https://twitter.com/yvoyer

**Comment by juliendufresne** [comment]
Hi @webdevilopers 

That's great to see that some other PHP Developpers are trying to implement Domain Driven Design concepts.

Please tell me what you are willing to do. I'll be happy to discuss about it.

You can also see other projects around DDD:
- A CQRS implementation by beberlei: [litecqrs](https://github.com/beberlei/litecqrs-php)
- The [Broadway](https://github.com/qandidate-labs/broadway) project

When I first created my project, the broadway project was in its early stage so I couldn't afford to use it in my company's project.

Side note:
- [domain-driven-design-bundle](https://github.com/php-ddd/domain-driven-design-bundle) is just a symfony integration of [domain-driven-design](https://github.com/php-ddd/domain-driven-design)
- [php-ddd-bundle](https://github.com/php-ddd/php-ddd-bundle) is just a symfony integration of [php-ddd/command](https://github.com/php-ddd/command) and [php-ddd/domain-event](https://github.com/php-ddd/domain-event)

**Comment by webdevilopers** [comment]
Thanks for joining @juliendufresne !

DDD has arrived in the PHP world. I guess most of us have read the red and the blue books.
My current code is mostly based on the DDD in PHP book:
https://leanpub.com/ddd-in-php

Personally I would like to create a community / organization that focusses on DDD best practices in the PHP world - discussing influences from the JAVA or .NET world.
It would be nice to define Naming Conventions.
And my personal priority is to implement @symfony Bundles into DDD Layers.

Of course our strategy should also enable other frameworks to easily integrate into our examples.

@yvoyer is currently filling the `DomainModel` of this example.

Maybe he can share his vision of "PHP-DDD" with us here?

BTW there is also this "Php Friends of DDD" group:
https://github.com/orgs/PhpFriendsOfDdd/people

**Comment by yvoyer** [comment]
Since developers that use specific framework usually do not share their applications (because the code belongs to theirs employers), there is not a lot of examples with integrating ddd concepts with frameworks. 

The way I see the project, is more an example on how to integrate a domain model with multiple context into multiple type of application framework. 

I don't think we should define standards since it all depends on the application (hierarchy,  naming etc).

I would just like to be able to have an available public application that can be installed easily by anyone, and that would just show example of using domain objects with a framework that could be used as references for discution. 

It happens sometime at work that I need to explain some concepts and using this project would be easier to explain the decoupling of domain model with infrastructure and frameworks.

**Comment by juliendufresne** [comment]
I see more what you want to achieve.
I don't think I'm gonna be a great help for you then.
The way one people Implement DDD is just a matter of taste.

It's a nice idea to create a demo application but I think you will need to use/create some separate library if you want people to implement DDD concepts in their own project.
I think of generic stuff like command or event bus for example.

One thing that we are missing in PHP is to have well-known dedicated library and almost everything is not dedicated to DDD.
The only thing that I could think of that is purely DDD, is the concept of Aggregate and BoundedContext but I don't see how it can be shared in a library because it's more about structuring your code into separate folder than a reusable set of classes.

**Comment by yvoyer** [comment]
@webdevilopers I think we could make an offer of our example to the (friends of ddd org)[https://github.com/orgs/PhpFriendsOfDdd]. They seems to be heading in the same direction as us, except they did not implemented an example yet.

Maybe we could transfer ownership to the org and continue the development there. What do you think?
