### ISSUE TITLE
How to return created entity with REST and DDD using POST request

### ISSUE THREAD

**Issue by borNfreee** [webdevilopers/php-ddd#29]
Hi,

I have an API and use command bus (the @thephpleague's Tactician) to handle commands.

The question is how to return new created entity after `POST` request in the body?

Controller's code (simplified):
```php
public function postAction(Request $request)
{
    $command = new CreateTaskCommand($request->get('name'), $request->get('startDate'));

    $this->get('command_bus')->handle($command);

    return $this->createView(???); // here I want to return new created entity as a response body with 201 CREATED status code
}
```

Keeping in mind that command bus can't return anything, what is the good way to get the created entity?

I found two recommendations:

* To use domain events and listeners, but it's not clear whether I need to iterated over recorded events in the controller and how to get created entity
* to fetch the created entity after it's created by the command bus, using the UUID

For the second point the code might look like:

```php
public function postAction(Request $request)
{
    $uuid = $request->get('uuid'); // or new TaskId();
    $command = new CreateTaskCommand($uuid, $request->get('name'), $request->get('startDate'));

    $this->get('command_bus')->handle($command);

    // here we fetch the new entity from the storage
    $entity = $someService->find($uuid);

    return $this->createView($entity);
}
```

How do you guys solve this case? Maybe creators of command buses (@matthiasnoback, @rosstuck) know something about this?

Thanks in advance.

**Comment by yvoyer** [comment]
When using a UUID (**recommended**), I usually create the new Id in the controller (as your example 2). That way you can fetch it after the handler is executed. 

When not using a UUID but an auto increment  (**not recommended**), you can can use a listener on the specific domain event, or ask the repository to generate an Id  (based on autoincrement) `$this->repository->generateTaskId ()`. The AI solution also comes with possible problems when 2 records are added simultaneously. 

On a side note, you should wrap the call to the handle with transaction, commit,  rollback, since if an error occurred during the creation, the repo would not have the entity, and the view might be broken.

**Comment by webdevilopers** [comment]
Welcome to PHPDDD @borNfreee !

@yvoyer has some good advice there! Start creating your own IDs (UUID recommended) - "TELL, don't ask"! This decouples your application from the persistence layer.
